spring: 
    h2:
        console:
            enabled: true
            path: /h2-console

    datasource:
        url: jdbc:h2:mem:bytebank;DB_CLOSE_DELAY=-1
        username: sa
        password:
        driverClassName: org.h2.Driver
    jpa:
        database-plataform: org.hibernate.dialect.H2Dialect
        hibernate.ddl-auto: update
        defer-datasource-initialization: true
        properties.hibernate.show_sql: false
        properties.hibernate.format_sql: false
